//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace Практическая_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public int admin_id { get; set; }

        public int account_id { get; set; }

        [Required(ErrorMessage = "Длина должна быть не более 24 символов")]
        [StringLength(24, MinimumLength = 1)]
        public string first_name { get; set; }

        [Required(ErrorMessage = "Длина должна быть не более 24 символов")]
        [StringLength(24, MinimumLength = 1)]
        public string last_name { get; set; }

        public string middle_name { get; set; }

        [Required(ErrorMessage = "Длина должна быть не более 64 символов")]
        [StringLength(64, MinimumLength = 1)]
        public string photo_path { get; set; }
    
        public virtual UserAccounts UserAccounts { get; set; }
    }
}
