//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практическая_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractsWithStores
    {
        public int contract_id { get; set; }
        public int store_id { get; set; }
        public Nullable<System.DateTime> contract_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
    
        public virtual Stores Stores { get; set; }
    }
}
