//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практическая_3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicRecordEntities : DbContext
    {
        public MusicRecordEntities()
            : base("name=MusicRecordEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlbumPreliminaryMeetings> AlbumPreliminaryMeetings { get; set; }
        public virtual DbSet<AlbumRequests> AlbumRequests { get; set; }
        public virtual DbSet<Albums> Albums { get; set; }
        public virtual DbSet<Artists> Artists { get; set; }
        public virtual DbSet<ContractsWithManufacturers> ContractsWithManufacturers { get; set; }
        public virtual DbSet<ContractsWithStores> ContractsWithStores { get; set; }
        public virtual DbSet<FinancialReports> FinancialReports { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<Producers> Producers { get; set; }
        public virtual DbSet<ProductionRequests> ProductionRequests { get; set; }
        public virtual DbSet<RecordingRooms> RecordingRooms { get; set; }
        public virtual DbSet<RevenueReports> RevenueReports { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RoomSchedules> RoomSchedules { get; set; }
        public virtual DbSet<Shipments> Shipments { get; set; }
        public virtual DbSet<Stores> Stores { get; set; }
        public virtual DbSet<StudioExpenses> StudioExpenses { get; set; }
        public virtual DbSet<Studios> Studios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserAccounts> UserAccounts { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
    }
}
