//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практическая_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordingRooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecordingRooms()
        {
            this.RoomSchedules = new HashSet<RoomSchedules>();
        }
    
        public int room_id { get; set; }
        public int studio_id { get; set; }
        public string name { get; set; }
        public string equipment { get; set; }
        public Nullable<decimal> hourly_rate { get; set; }
    
        public virtual Studios Studios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomSchedules> RoomSchedules { get; set; }
    }
}
