//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практическая_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipments
    {
        public int shipment_id { get; set; }
        public int album_id { get; set; }
        public int store_id { get; set; }
        public Nullable<System.DateTime> shipment_date { get; set; }
        public int quantity { get; set; }
        public Nullable<decimal> price_per_unit { get; set; }
    
        public virtual Albums Albums { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
